config/routes.rb
Rails.application.routes.draw do
 

  resources :comments
 

  resources :songs do
    resource :like, module: :songs
    resources :comments
  end

  devise_for :preachers
  resources :preachers do

  end

resources :preaches
resources :videos

  
  root 'pages#index'
  
  get '/home' => 'pages#home' # override default routes.

 get '/preacher/:id' => 'preachers#show'

 get '/explore' => 'pages#explore'

  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :preacher
  belongs_to :song
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 before_action :set_comment, only: [:show, :edit, :update, :destroy]
before_filter :authenticate_preacher!
  before_action :set_song

def index
    @comments = Comment.all
    #respond_with(@comments)
  end
  # POST /comments
  # POST /comments.json
  def create

    @song = Song.friendly.find(params[:song_id])
    @comment = @song.comments.new(comment_params) #Important for comments to show on songs page
    @comment.preacher = current_preacher

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @song, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_song
    #@song = Song.find(params[:song_id])
    @song = Song.friendly.find(params[:song_id])
     
   end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:song_id, :body, :preacher_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<!-- ============================================
          LATEST POSTS LIST
          =============================================== -->



         <!-- TOP BLOCK -->
          <!--div class="row">
            <div class="col-md-8">
              <div class="panel" data-fill-color="true" style="height:268px">
                <div class="panel-heading">
                  <div class="panel-control pull-right">
                    <a href="#" class="btn btn-icon">View all</a>
                  </div>
                  <h3 class="panel-title">Top Sellers</h3>
                </div>
                

                <div class="list-group">
                  <div class="list-group-item">
                    <div class="media">
                      <div class="media-left">
                        <div class="kit-avatar kit-avatar-28 no-border mr-1x">
                          <img class="media-object" src="images/dummy/uifaces5.jpg">
                        </div>
                      </div>
                      <div class="media-body media-middle">
                        <div class="dropdown pull-right">
                          <button class="btn btn-xs btn-default btn-icon dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><i class="icon-options-vertical text-muted"></i></button>
                          <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#">View profile</a></li>
                            <li><a href="#">View projects</a></li>
                            <li><a href="#">Send a message</a></li>
                          </ul>
                        </div-->

                         <!--img src="images/dummy/people2.jpg" alt="avatar"-->

 
          





 <div class="panel mb-1x">
            <div class="panel-body">
              <div class="row">

              <div class="col-lg-1 col-md-1 col-sm-1 col-xs-6 hidden-xs">
               

                <div class="pt-1x"> 

                <!--a href="#" class="kit-avatar kit-avatar-28 no-border mr-1x pull-left kit-avatar-fw">
                  <%# image_tag("fallback/unknown-profile.jpg", :class => "kit-avatar kit-avatar-28 no-border mr-1x pull-left kit-avatar-fw") %>
                 </a-->




            <% if comment.preacher.profilephoto? %>
            <%=link_to (image_tag comment.preacher.profilephoto.url(:small), :class => "kit-avatar kit-avatar-28 no-border mr-1x pull-left kit-avatar-fw comment-img"), preacher_path(comment.preacher_id) %>
            <% else %> 
            <%= image_tag("fallback/unknown-profile.jpg", :class => "kit-avatar kit-avatar-28 no-border mr-1x pull-left kit-avatar-fw comment-img") %></a></li>
           <% end %> 
           

            </div>


           </div><!-- /.cols -->
                

                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-9">

               



                <!-- inner row for name-->

                <div class="row">

                <div class="col-lg-8 col-md-8 col-sm-8 col-xs-9">


                <small><%= comment.preacher.firstname + " " + "says" if comment.preacher.firstname %></small>
                </div>

                </div>

                <!-- End inner row for name-->


                  
                 
                  
                <div class="pt-1x"><%= best_in_place_if comment.preacher == current_preacher, comment, :body,  :as => :textarea, :ok_button => 'Save ',  :cancel_button => ' Cancel' %></div>
                
                </div><!-- /.cols -->

               
                <div class="col-lg-2 col-md-2 col-sm-2 col-xs-3 hidden-xs">
                  <div class="pt-1x"><%= time_ago_in_words(comment.created_at) %> ago</div>
                </div><!-- /.cols -->

              
                <div class="col-lg-1 col-md-1 col-sm-1 col-xs-3 text-right pull-right">

                <div class="dropdown pull-right">
                          <button class="btn btn-xs btn-default btn-icon dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><i class="fa fa-ellipsis-v"></i></button>
                          <ul class="dropdown-menu dropdown-menu-right">
                           

                            <li>
                            
                            <% if comment.preacher == current_preacher -%>
                            <h5><%= link_to 'Delete comment', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "label label-danger margin-left10" %></h5>
                            
                            
                           
                              </li>
                              <% end %>


                            <li><a href="#">Report spam or abuse</a></li>
                            <li><a href="#">Send a message</a></li>
                          </ul>
                  </div>
                  <!--a href="#" class="btn btn-primary">Edit</a-->
                </div><!-- /.cols -->

              

              </div><!-- /.row -->
            </div><!-- /.panel-body -->
          </div><!-- /.panel -->



          <!-- End -->


  






  

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :song_id %><br>
    <%= f.number_field :song_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :preacher_id %><br>
    <%= f.text_field :preacher_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>



<table>
  <thead>
    <tr>
      <th>Song</th>
      <th>Body</th>
      <th>Preacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.song_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.preacher %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
 <div class="alert alert-success fade in">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <%= notice %>.
                </div>






<p>
  <strong>Song:</strong>
  <%= @comment.song_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Preacher:</strong>
  <%= @comment.preacher %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>