config/routes.rb
Rails.application.routes.draw do
 

  resources :comments
 

  resources :songs do
    resource :like, module: :songs
    resources :comments
  end

  devise_for :preachers
  resources :preachers do

  end

resources :preaches
resources :videos

  
  root 'pages#index'
  
  get '/home' => 'pages#home' # override default routes.

 get '/preacher/:id' => 'preachers#show'

 get '/explore' => 'pages#explore'

  
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :preacher

  is_impressionable

  #carrierWave uploader
    mount_uploader :soundcover, SoundcoverUploader
    mount_uploader :sound, SoundUploader
   

  validates :preacher_id, presence: true

  has_many :likes, dependent: :destroy # remove a preacher's videos if his account is deleted.
  has_many :comments, dependent: :destroy # remove a preacher's videos if his account is deleted.
  


   extend FriendlyId
  friendly_id :displayname, use: :slugged



end

app/controllers/songs/likes_controller.rb
class Songs::LikesController < ApplicationController
  before_action :authenticate_preacher!
  before_action :set_song

  def create
    @song.likes.where(preacher_id: current_preacher.id).first_or_create

    respond_to do |format|
      format.html {redirect_to @song}
      format.js
    end
  end

    def destroy
      @song.likes.where(preacher_id: current_preacher.id).destroy_all

      respond_to do |format|
      format.html {redirect_to @song}
      format.js
      
    end
    
  end

  private

   def set_song
    #@song = Song.find(params[:song_id])
    @song = Song.friendly.find(params[:song_id])
     
   end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  impressionist :actions=>[:show,:index]

  before_action :set_song, only: [:show, :edit, :update, :destroy]



  # GET /audios
  # GET /audios.json
  def index
    @songs = Song.all.order('created_at DESC')
    @newPreach = Preach.new
    @newVideo = Video.new
    @newSong = Song.new
  end

  # GET /audios/1
  # GET /audios/1.json
  def show
  	impressionist(@song)
    @newPreach = Preach.new
    @newVideo = Video.new
    @newSong = Song.new

  	
    @song = Song.friendly.find(params[:id])
  if request.path != song_path(@song)
    redirect_to @song, status: :moved_permanently
  else
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end
end


  # GET /audios/new
  def new
    
    @song = Song.new 
    
  end

  # GET /audios/1/edit
  def edit
    
  end

  # POST /audios
  # POST /audios.json
  def create
    @song = Song.new(_params)
    
    
     @song.preacher_id = current_preacher.id # assign the video to the preacher who created it.

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Audio was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /audios/1
  # PATCH/PUT /audios/1.json
  def update
    
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Audio was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /audios/1
  # DELETE /audios/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to audios_url, notice: 'Audio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :desc, :preacher_id, :sound, :soundcover, :artist, :date_released, :genre, :lyrics)
    end


end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this audio from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :title, autofocus: true, :placeholder => 'Song title', class: "form-control" %>
                <p></p>

                <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <p></p>
                <%= f.text_area :desc, autofocus: true, :placeholder => 'Description', class: "form-control" %>
                <div class="field">
                <div class="field">
                <%= f.label :add_song %><br>
                <%= f.file_field :sound %>
              </div>
              <div class="field">
                <%= f.label :add_cover_image %><br>
                <%= f.file_field :soundcover %>
              </div>
 

  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/songs/_likes.html.erb
<% if preacher_signed_in? && current_preacher.likes?(song) %>
  <%= link_to "", song_like_path(song), method: :delete, remote: true, :class=>"fa fa-heart fa-2x" %>
<% else %>
<large><%= link_to "", song_like_path(song), method: :post, remote: true, :class=>"fa fa-heart-o fa-2x" %></large>
<% end %>
<br>
<strong><%= song.likes.count %></strong>

app/views/songs/_songcomments.html.erb
<h3 class="comments_title">
  

  <i class="fa fa-comment fa" style="color:#337ab7"></i><%= @song.comments.size %> <%= "Comment".pluralize(@song.comments.count) %> 

  

  <div class="progress progress-xs">
                        <div class="progress-bar progress-bar-danger" style="width:28%"></div>
                      </div>

                    
</h3>




<%= form_for [@song, Comment.new]  do |f| %>
  
  <div class="field ">
     <%= f.text_area :body, :autofocus => true, :placeholder => 'write comment...', :class => "form-control" %>
  </div>

 
  <h5><%= f.submit "Post", :class => "btn btn-primary" %></h5>

<% end %>

<br>





<div id="comments">
  <%= render :partial => @song.comments %>
</div>

<br />

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index2.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th>Soundcover</th>
      <th>Sound</th>
      <th>Date released</th>
      <th>Genre</th>
      <th>Lyrics</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.desc %></td>
        <td><%= song.soundcover %></td>
        <td><%= song.sound %></td>
        <td><%= song.date_released %></td>
        <td><%= song.genre %></td>
        <td><%= song.lyrics %></td>
        <td><%= song.artist %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>