config/routes.rb
Rails.application.routes.draw do
 

  resources :comments
 

  resources :songs do
    resource :like, module: :songs
    resources :comments
  end

  devise_for :preachers
  resources :preachers do

  end

resources :preaches
resources :videos

  
  root 'pages#index'
  
  get '/home' => 'pages#home' # override default routes.

 get '/preacher/:id' => 'preachers#show'

 get '/explore' => 'pages#explore'

  
end

app/views/layouts/_nav.html.erb
<!-- we will render seperate nav bars depending on if the user is signed in or not. -->
<% if !preacher_signed_in? %>
  <%= render '/layouts/nav_guest' %>
<% else %>
  <%= render '/layouts/nav_preacher' %>
<% end %>

app/views/layouts/_nav3.html.erb
<ul class="nav nav-tabs nav-justified drop" role="tablist">
                
                <li role="presentation"><a href="/songs" aria-controls="profile" role="link">Music</a></li>

                <li role="presentation"><a href="/preaches" aria-controls="messages" role="link">Preaches</a></li>

                <li role="presentation"><a href="/songs" aria-controls="profile" role="link">Sermons</a></li>


                <li role="presentation"><a href="/videos" aria-controls="messages" role="link">Videos</a></li>
                 
                <li role="presentation"><a href="/explore" aria-controls="home" role="link">All</a></li>
                
              </ul>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-inverse bs-docs-nav navbar-fixed-top sticky-navigation">
  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/">Home </a></li>
        <li><a href="/songs">Explore </a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Profile<span class="caret"></span></a>
          
          <ul class="dropdown-menu">
          <li><%= link_to('Sign In', new_preacher_session_path) %></li>
            <li><%= link_to('Sign Up', new_preacher_registration_path) %></li>
            <li role="separator" class="divider"></li>
            
          </ul>
          
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_preacher.html.erb
<a name="top"></a>
<nav class="navbar navbar-inverse bs-docs-nav navbar-fixed-top sticky-navigation">
  

  <div class="container-fluid container">
    <!-- Brand and toggle get grouped for better mobile display -->
    

    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed bgblack" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    
   
    <%= link_to image_tag("preachout.png", :class => "navbar-brand thum35"), root_path %>
   
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/home">Home </a></li>
        <li><a href="/explore">Explore </a></li>
        <li><a href="/home">Notifications</a></li>
        <li><a href="/home">Messages </a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search PreachOut">
            </div>
          </form>
        </li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag(current_preacher.profilephoto.url(:small), :class => "rounded-img",  :height => "25px", :width => "25px" ) %> <span class="caret"></span></a>




          
          <ul class="dropdown-menu">
            <li><a href="/preacher/<%= current_preacher.displayname %>">Profile</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Settings', edit_preacher_registration_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Log Out', destroy_preacher_session_path, :method => :delete) %></li>
          </ul>
          
         <li type="button" class="btn btn-primary navbar-btn">PreachOut</li>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_preacher2.html.erb
 <!-- STICKY NAVIGATION -->
            <div class="navbar navbar-inverse bs-docs-nav navbar-fixed-top sticky-navigation" role="navigation">
                <div class="container">
                    <div class="navbar-header">

                        <!-- LOGO ON STICKY NAV BAR -->
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#stamp-navigation">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-grid-2x2"></span>
                        </button>

                        <!-- LOGO -->
                        <a class="navbar-brand" href="#">
                            <img src="images/logo-nav.png" alt="">
                        </a>

                    </div>

                    <!-- TOP BAR -->
                    <div class="navbar-collapse collapse" id="stamp-navigation">

                        <!-- NAVIGATION LINK -->
                        <ul class="nav navbar-nav navbar-left main-navigation small-text">
                            <li><a href="#section2">Why Us?</a>
                            </li>
                            <li><a href="#section5">Benefits</a>
                            </li>
                            <li><a href="#section6">Pricing</a>
                            </li>
                            <li><a href="#section7">Explore</a>
                            </li>
                            <li><a href="#section10">Testimonials</a>
                            </li>
                            <!-- <li><a href="http://example.com" class="external">External Link Example</a></li> -->
                        </ul>

                        <!-- LOGIN REGISTER -->
                        <ul class="nav navbar-nav navbar-right login-register small-text">
                            <li class="login js-login"><a href="#">Login</a>
                            </li>
                            <li class="register-button js-register inpage-scroll"><a href="#home" class="navbar-register-button">Get Started</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /END CONTAINER -->
            </div>
            <!-- /END STICKY NAVIGATION -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pout</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>





<%= render '/layouts/nav' %>


<span class="notice"><%= notice %></span> 
<span class="alert"><%= alert %></span> 




<div id="wrapper">
        <div class="overlay"></div>


<p></p>

<p></p>

<p></p>

<p></p>

        <!-- Sidebar -->
        <nav class="navbar navbar-inverse navbar-fixed-top pullsidenav" id="sidebar-wrapper" role="navigation">
          
            <ul class="nav sidebar-nav">
                <!--li class="sidebar-brand">
                    <a href="#">
                       Brand
                    </a-->
                </li>
                
                <li>
                    <a href="/preaches">Preaches</a>
                </li>
                <li>
                    <a href="/songs">Music</a>
                </li>
                <li>
                    <a href="/videos">Video</a>
                </li>
                <!--li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Works <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li class="dropdown-header">Dropdown heading</li>
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li-->
                <li>
                    <a href="#">About PreachOut</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
                <li>
                    <a href="https://twitter.com/maridlcrmn">Follow on Facebook</a>
                </li>
                <li>
                    <a href="https://twitter.com/maridlcrmn">Follow on Twitter</a>
                </li>
            </ul>
        </nav>


        <!-- /#sidebar-opener -->  





        <div id="page-content-wrapper">
            <button type="button" class="hamburger is-closed" data-toggle="offcanvas">
                <span class="hamb-top"></span>
            <span class="hamb-middle"></span>
        <span class="hamb-bottom"></span>
            </button>



<%= yield %>

</div>
</div>




 

</body>
</html>